---
plex_nfs_path: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633738376533656339393666333262343532393136666538336239373039323737313266366436
          3466353563333363636339643334643963336663633934300a663733353166623232653463333262
          65386638353731353233333932336331633235613765333837356161636165343463646662613163
          3465663265396235660a373931306534616232396533656532366162386435363938306430383762
          33313534393961653237663931653130306264646137356261393436613563326537353532613835
          3032333638353532656436643866366236623130333261313564
